/**
 * Solana Integration Service
 *
 * Manages on-chain prediction market state via Anchor (Solana) integration.
 * Handles:
 *  - Market account deserialisation (read market state)
 *  - Bet account reading
 *  - Settlement transaction signing (keeper bot)
 *  - Monitoring on-chain state changes
 *
 * Two modes:
 *  - REAL — reads/writes the deployed prediction-market program
 *    (C5vNdxLcaMriywhQJzv3Dv8PKDfkfnKWHvqCVnqgEQE5 on Devnet) using the
 *    Anchor IDL bundled at backend/idl/prediction_market.json. Reads work
 *    without a keeper key; settlement requires SOLANA_KEEPER_PRIVATE_KEY.
 *  - MOCK — in-memory state for tests and offline development.
 */

import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { getLogger } from '../logger.js';
import { config } from '../config.js';

const logger = getLogger();

const __dirname = path.dirname(fileURLToPath(import.meta.url));

/** TxLINE Devnet program (settlement oracle). */
export const TXLINE_PROGRAM_ID = '6pW64gN1s2uqjHkn1unFeEjAwJkPGHoppGvS715wyP2J';

// ─── Types ───────────────────────────────────────────────────────────────────

export interface SolanaMarketAccount {
  authority: string;
  fixtureId: string;
  outcome0Pool: number;  // home_win pool in lamports
  outcome1Pool: number;  // away_win pool in lamports
  outcome2Pool: number;  // draw pool in lamports
  locked: boolean;
  settled: boolean;
  result: number;        // 0=home_win, 1=away_win, 2=draw
  totalBets: number;
}

export interface SolanaBetAccount {
  user: string;
  market: string;
  outcome: number;
  amount: number;        // lamports
  odds: number;          // scaled decimal odds (e.g. 200 = 2.0)
  claimed: boolean;
}

export interface SolanaServiceOptions {
  rpcUrl?: string;
  privateKey?: string;
  programId?: string;
  /** If true, use mock data instead of real RPC calls (default: true for dev). */
  mockMode?: boolean;
}

// ─── Service ─────────────────────────────────────────────────────────────────

export class SolanaService {
  private options: Required<SolanaServiceOptions>;
  private anchor: typeof import('@coral-xyz/anchor') | null = null;
  private connection: import('@solana/web3.js').Connection | null = null;
  private wallet: import('@coral-xyz/anchor').Wallet | null = null;
  private program: import('@coral-xyz/anchor').Program | null = null;

  // In-memory mock state for development
  private mockMarkets: Map<string, SolanaMarketAccount> = new Map();
  private mockBets: Map<string, SolanaBetAccount[]> = new Map();

  constructor(options?: SolanaServiceOptions) {
    this.options = {
      rpcUrl: options?.rpcUrl ?? config.solanaRpcUrl,
      privateKey: options?.privateKey ?? config.solanaKeeperPrivateKey,
      programId: options?.programId ?? config.solanaProgramId,
      mockMode: options?.mockMode ?? (!config.solanaKeeperPrivateKey && !config.solanaProgramId),
    };

    if (!this.options.mockMode) {
      this.initialiseRealConnection();
    } else {
      logger.info('Solana service running in MOCK mode — no on-chain operations');
    }
  }

  // ─── Initialisation ───────────────────────────────────────────────────────

  private async initialiseRealConnection(): Promise<void> {
    try {
      const anchor = await import('@coral-xyz/anchor');
      const web3 = await import('@solana/web3.js');
      this.anchor = anchor;

      this.connection = new web3.Connection(this.options.rpcUrl, 'confirmed');

      if (this.options.privateKey) {
        // KEEPER_PRIVATE_KEY is expected as base64-encoded secret key bytes.
        // (Base58 is not a Node Buffer encoding.)
        const keypair = web3.Keypair.fromSecretKey(
          Buffer.from(this.options.privateKey, 'base64'),
        );
        this.wallet = new anchor.Wallet(keypair);
      }

      if (this.options.programId) {
        const idl = await this.fetchIdl();
        if (idl) {
          // Reads need no signer — use the keeper wallet if present,
          // otherwise an ephemeral throwaway keypair.
          const provider = new anchor.AnchorProvider(
            this.connection,
            this.wallet ?? new anchor.Wallet(web3.Keypair.generate()),
            { commitment: 'confirmed' },
          );
          this.program = new anchor.Program(
            idl as import('@coral-xyz/anchor').Idl,
            provider,
          );
        }
      }

      logger.info(
        {
          rpcUrl: this.options.rpcUrl,
          programId: this.options.programId,
          keeper: this.wallet?.publicKey.toBase58() ?? null,
        },
        'Solana real connection initialised',
      );
    } catch (error) {
      logger.error({ error }, 'Failed to initialise Solana connection, falling back to mock mode');
      this.options.mockMode = true;
    }
  }

  /**
   * Load the prediction-market IDL from disk. Generated by `anchor build`
   * and vendored into the repo so the backend deploys standalone.
   */
  private async fetchIdl(): Promise<unknown | null> {
    const candidates = [
      path.join(process.cwd(), 'idl/prediction_market.json'),
      path.join(__dirname, '../../idl/prediction_market.json'),
      path.join(__dirname, '../../../contracts/prediction-market/target/idl/prediction_market.json'),
    ];
    for (const candidate of candidates) {
      try {
        const idl = JSON.parse(readFileSync(candidate, 'utf8'));
        logger.info({ path: candidate }, 'Loaded prediction-market IDL');
        return idl;
      } catch {
        // try next candidate
      }
    }
    logger.warn('IDL not found on disk — on-chain reads unavailable, using mock data');
    return null;
  }

  // ─── Public API (works in both mock and real modes) ────────────────────────

  /**
   * Read a prediction market account on-chain.
   * Returns mock data if in mock mode or if real RPC fails.
   */
  async getMarketAccount(marketAddress: string): Promise<SolanaMarketAccount | null> {
    if (this.options.mockMode) {
      return this.mockMarkets.get(marketAddress) ?? null;
    }

    try {
      if (!this.program) throw new Error('Anchor program not initialised');
      const account = await (this.program.account as Record<string, any>).market.fetchNullable(
        marketAddress,
      );
      if (!account) return null;

      const statusKey = Object.keys(account.status)[0];
      const pools: number[] = account.outcomePools.map((p: { toNumber(): number }) => p.toNumber());
      return {
        authority: this.options.programId,
        fixtureId: account.matchId,
        outcome0Pool: pools[0] ?? 0,
        outcome1Pool: pools[1] ?? 0,
        outcome2Pool: pools[2] ?? 0,
        locked: statusKey === 'locked',
        settled: statusKey === 'settled',
        result: account.winningOutcome,
        totalBets: 0, // not tracked on-chain; derive via getBetAccounts()
      };
    } catch (error) {
      logger.error({ error, marketAddress }, 'Failed to read market account, falling back to mock');
      return this.mockMarkets.get(marketAddress) ?? null;
    }
  }

  /**
   * Read bet accounts for a market.
   */
  async getBetAccounts(marketAddress: string): Promise<SolanaBetAccount[]> {
    if (this.options.mockMode) {
      return this.mockBets.get(marketAddress) ?? [];
    }

    try {
      if (!this.program) throw new Error('Anchor program not initialised');
      // Bet layout: 8-byte discriminator, then `market: Pubkey` at offset 8.
      const accounts = await (this.program.account as Record<string, any>).bet.all([
        { memcmp: { offset: 8, bytes: marketAddress } },
      ]);
      return accounts.map((a: any) => ({
        user: a.account.bettor.toBase58(),
        market: a.account.market.toBase58(),
        outcome: a.account.outcomeIndex,
        amount: a.account.amount.toNumber(),
        odds: 0, // pool-based market — odds are implied by pool ratios
        claimed: a.account.claimed,
      }));
    } catch (error) {
      logger.error({ error, marketAddress }, 'Failed to read bet accounts, falling back to mock');
      return this.mockBets.get(marketAddress) ?? [];
    }
  }

  /**
   * Submit a settlement transaction as keeper bot.
   * This signs and sends the tx to update the on-chain market state.
   */
  async settleMarket(
    marketAddress: string,
    outcome: number,  // 0=home_win, 1=away_win, 2=draw
    merkleProof: { root: string; proof: string[]; leaf: string },
    /** On-chain TxLINE proof account holding the Merkle proof to consume. */
    proofAccount?: string,
  ): Promise<{ signature: string } | null> {
    if (this.options.mockMode) {
      // Update mock state
      const market = this.mockMarkets.get(marketAddress);
      if (market) {
        market.settled = true;
        market.result = outcome;
        this.mockMarkets.set(marketAddress, market);
      }
      logger.info({ marketAddress, outcome }, 'Mock settlement submitted');
      return { signature: `mock-sig-${Date.now()}` };
    }

    try {
      if (!this.program) throw new Error('Anchor program not initialised');
      if (!this.wallet) {
        throw new Error('SOLANA_KEEPER_PRIVATE_KEY not configured — keeper cannot sign settlements');
      }
      if (!proofAccount) {
        throw new Error('TxLINE proof account address required for on-chain settlement');
      }

      const web3 = await import('@solana/web3.js');
      const programId = new web3.PublicKey(this.options.programId);
      const txlineProgram = new web3.PublicKey(TXLINE_PROGRAM_ID);
      const [configPda] = web3.PublicKey.findProgramAddressSync(
        [Buffer.from('config')],
        programId,
      );
      const [txlineState] = web3.PublicKey.findProgramAddressSync(
        [Buffer.from('state')],
        txlineProgram,
      );

      // settle_market forwards proof_data verbatim after the validate_stat
      // discriminator, so the payload is assembled entirely off-chain here.
      // Current encoding: match-id hash (32 bytes, from the proof bundle's
      // Merkle root) ++ outcome (1 byte). To settle against the real
      // txoracle, borsh-serialize its validate_stat args instead
      // (ts, fixture_summary, fixture_proof, main_tree_proof, predicate,
      // stat_a, stat_b, op — see scripts/idl/txoracle.json); no program
      // change is needed.
      const matchIdBytes = Buffer.alloc(32);
      Buffer.from(merkleProof.root.replace(/^0x/, ''), 'hex').copy(matchIdBytes);
      const proofData = Buffer.concat([matchIdBytes, Buffer.from([outcome])]);

      const signature = await (this.program.methods as Record<string, any>)
        .settleMarket(outcome, proofData)
        .accountsPartial({
          market: new web3.PublicKey(marketAddress),
          config: configPda,
          admin: this.wallet.publicKey,
          txlineProgram,
          txlineState,
          txlineProofAccount: new web3.PublicKey(proofAccount),
        })
        .rpc();

      logger.info({ marketAddress, outcome, signature }, 'On-chain settlement submitted');
      return { signature };
    } catch (error) {
      logger.error({ error, marketAddress }, 'Failed to settle market on-chain');
      return null;
    }
  }

  /**
   * Monitor on-chain market state. Returns key state indicators.
   */
  async monitorMarket(marketAddress: string): Promise<{
    locked: boolean;
    settled: boolean;
    totalPool: number;
  }> {
    const account = await this.getMarketAccount(marketAddress);
    if (!account) {
      return { locked: false, settled: false, totalPool: 0 };
    }

    return {
      locked: account.locked,
      settled: account.settled,
      totalPool: account.outcome0Pool + account.outcome1Pool + account.outcome2Pool,
    };
  }

  /**
   * Get the keeper wallet balance (if connected).
   */
  async getKeeperBalance(): Promise<number | null> {
    if (this.options.mockMode) {
      return 100_000_000; // 0.1 SOL in lamports
    }

    try {
      if (!this.wallet) return null;
      const balance = await this.connection!.getBalance(this.wallet.publicKey);
      return balance;
    } catch (error) {
      logger.error({ error }, 'Failed to get keeper balance');
      return null;
    }
  }

  /**
   * Get the keeper wallet public key.
   */
  getKeeperPublicKey(): string | null {
    if (this.options.mockMode) {
      return 'mock-keeper-public-key';
    }
    return this.wallet?.publicKey.toBase58() ?? null;
  }

  // ─── Mock helpers (for seeding test data) ─────────────────────────────────

  /** Seed a mock market account (for testing/dev). */
  seedMockMarket(address: string, data: Partial<SolanaMarketAccount>): void {
    const defaultMarket: SolanaMarketAccount = {
      authority: 'mock-authority',
      fixtureId: 'mock-fixture',
      outcome0Pool: 100_000_000,  // 0.1 SOL
      outcome1Pool: 150_000_000,  // 0.15 SOL
      outcome2Pool: 75_000_000,   // 0.075 SOL
      locked: false,
      settled: false,
      result: 0,
      totalBets: 0,
    };
    this.mockMarkets.set(address, { ...defaultMarket, ...data });
  }

  /** Seed mock bet accounts for a market. */
  seedMockBets(marketAddress: string, bets: SolanaBetAccount[]): void {
    this.mockBets.set(marketAddress, bets);
  }
}

// ─── Zod schemas for validation ──────────────────────────────────────────────

import { z } from 'zod';

export const SettleMarketSchema = z.object({
  outcome: z.union([z.literal(0), z.literal(1), z.literal(2)]),
  merkleProof: z.object({
    root: z.string(),
    proof: z.array(z.string()),
    leaf: z.string(),
  }),
});

export type SettleMarketInput = z.infer<typeof SettleMarketSchema>;
