/**
 * GoalChain Solana client — real on-chain betting via the deployed
 * prediction-market Anchor program on Devnet.
 *
 * Program: C5vNdxLcaMriywhQJzv3Dv8PKDfkfnKWHvqCVnqgEQE5
 *
 * PDAs (must mirror programs/prediction-market/src/lib.rs):
 *   Market: ["market", market_id (u64 LE)]
 *   Bet:    ["bet", market_pda, bettor, [outcome_index]]
 *   Config: ["config"]
 */

import {
  Connection,
  PublicKey,
  SystemProgram,
  SYSVAR_CLOCK_PUBKEY,
  LAMPORTS_PER_SOL,
} from '@solana/web3.js';
import { AnchorProvider, BN, Program, type Idl } from '@coral-xyz/anchor';
import type { WalletContextState } from '@solana/wallet-adapter-react';
import { Buffer } from 'buffer';
import rawIdl from './idl/prediction_market.json';

const SOLANA_RPC = process.env.NEXT_PUBLIC_SOLANA_RPC || 'https://api.devnet.solana.com';
const PROGRAM_ID = new PublicKey(
  process.env.NEXT_PUBLIC_PREDICTION_PROGRAM_ID || (rawIdl as { address: string }).address,
);

// The IDL is generated by `anchor build` (contracts/prediction-market/target/idl)
// and copied here. Its `address` field points at the Devnet deployment.
const IDL = rawIdl as Idl;

export interface PlaceBetResult {
  success: boolean;
  signature: string;
  error?: string;
}

export interface OnchainMarket {
  address: string;
  marketId: number;
  matchId: string;
  status: 'open' | 'locked' | 'settled' | 'cancelled';
  outcomes: string[];
  outcomePools: number[]; // lamports
  totalPool: number; // lamports
  winningOutcome: number | null;
  lockTime: number; // unix ts
  resolveTime: number; // unix ts
}

/** Derive the market PDA for a numeric on-chain market id. */
export function deriveMarketPda(marketId: number | bigint): PublicKey {
  const idBuf = Buffer.alloc(8);
  idBuf.writeBigUInt64LE(BigInt(marketId));
  return PublicKey.findProgramAddressSync([Buffer.from('market'), idBuf], PROGRAM_ID)[0];
}

/** Derive the bet PDA for (market, bettor, outcomeIndex). */
export function deriveBetPda(
  market: PublicKey,
  bettor: PublicKey,
  outcomeIndex: number,
): PublicKey {
  return PublicKey.findProgramAddressSync(
    [Buffer.from('bet'), market.toBuffer(), bettor.toBuffer(), Buffer.from([outcomeIndex])],
    PROGRAM_ID,
  )[0];
}

/**
 * Resolve a UI market to its on-chain market PDA.
 * Live (backend-managed) markets carry the address directly; demo markets
 * carry the numeric id the PDA derives from. Null → not on-chain.
 */
export function resolveMarketPda(market: {
  onchainMarketId?: number;
  onchainAddress?: string;
}): PublicKey | null {
  if (market.onchainAddress) {
    try {
      return new PublicKey(market.onchainAddress);
    } catch {
      return null;
    }
  }
  if (market.onchainMarketId !== undefined) return deriveMarketPda(market.onchainMarketId);
  return null;
}

/** Read-only wallet stub so account reads work before a wallet connects. */
const READ_ONLY_WALLET = {
  publicKey: PublicKey.default,
  signTransaction: async () => {
    throw new Error('Read-only wallet cannot sign');
  },
  signAllTransactions: async () => {
    throw new Error('Read-only wallet cannot sign');
  },
};

class SolanaClient {
  private connection: Connection;

  constructor() {
    this.connection = new Connection(SOLANA_RPC, 'confirmed');
  }

  getConnection(): Connection {
    return this.connection;
  }

  getProgramId(): PublicKey {
    return PROGRAM_ID;
  }

  /** Build an Anchor Program bound to the given wallet (or read-only). */
  private getProgram(wallet?: WalletContextState): Program {
    const anchorWallet =
      wallet && wallet.publicKey && wallet.signTransaction && wallet.signAllTransactions
        ? {
            publicKey: wallet.publicKey,
            signTransaction: wallet.signTransaction,
            signAllTransactions: wallet.signAllTransactions,
          }
        : READ_ONLY_WALLET;

    const provider = new AnchorProvider(this.connection, anchorWallet as never, {
      commitment: 'confirmed',
    });
    return new Program(IDL, provider);
  }

  /**
   * Place a real bet on-chain: transfers `amountSol` from the connected
   * wallet into the market PDA escrow and creates the Bet account.
   */
  async placeBet(
    wallet: WalletContextState,
    marketPda: PublicKey,
    outcomeIndex: number,
    amountSol: number,
  ): Promise<PlaceBetResult> {
    try {
      if (!wallet.publicKey) throw new Error('Wallet not connected');
      if (!wallet.signTransaction) throw new Error('Wallet does not support signing');

      const lamports = Math.round(amountSol * LAMPORTS_PER_SOL);
      if (lamports <= 0) throw new Error('Amount must be greater than zero');

      const betPda = deriveBetPda(marketPda, wallet.publicKey, outcomeIndex);
      const program = this.getProgram(wallet);

      const signature = await program.methods
        .placeBet(new BN(lamports), outcomeIndex)
        .accountsPartial({
          market: marketPda,
          bet: betPda,
          bettor: wallet.publicKey,
          systemProgram: SystemProgram.programId,
          clock: SYSVAR_CLOCK_PUBKEY,
        })
        .rpc();

      return { success: true, signature };
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      console.error('[GoalChain] placeBet failed:', error);
      return { success: false, signature: '', error: friendlyBetError(message) };
    }
  }

  /**
   * Claim winnings from a settled market for the bet the wallet placed
   * on `outcomeIndex`.
   */
  async claimWinnings(
    wallet: WalletContextState,
    marketPda: PublicKey,
    outcomeIndex: number,
  ): Promise<PlaceBetResult> {
    try {
      if (!wallet.publicKey) throw new Error('Wallet not connected');

      const betPda = deriveBetPda(marketPda, wallet.publicKey, outcomeIndex);
      const program = this.getProgram(wallet);

      const signature = await program.methods
        .claimWinnings()
        .accountsPartial({
          market: marketPda,
          bet: betPda,
          winner: wallet.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .rpc();

      return { success: true, signature };
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      console.error('[GoalChain] claimWinnings failed:', error);
      return { success: false, signature: '', error: message };
    }
  }

  /** Fetch and normalise an on-chain market account. Returns null if absent. */
  async getOnchainMarket(marketPda: PublicKey): Promise<OnchainMarket | null> {
    try {
      const program = this.getProgram();
      const account = (await (program.account as never as Record<
        string,
        { fetchNullable: (addr: PublicKey) => Promise<Record<string, unknown> | null> }
      >).market.fetchNullable(marketPda)) as {
        marketId: BN;
        matchId: string;
        status: Record<string, unknown>;
        outcomes: string[];
        outcomePools: BN[];
        totalPool: BN;
        winningOutcome: number;
        lockTime: BN;
        resolveTime: BN;
      } | null;
      if (!account) return null;

      const statusKey = Object.keys(account.status)[0] as OnchainMarket['status'];
      return {
        address: marketPda.toBase58(),
        marketId: account.marketId.toNumber(),
        matchId: account.matchId,
        status: statusKey,
        outcomes: account.outcomes,
        outcomePools: account.outcomePools.map((p) => p.toNumber()),
        totalPool: account.totalPool.toNumber(),
        winningOutcome: account.winningOutcome === 255 ? null : account.winningOutcome,
        lockTime: account.lockTime.toNumber(),
        resolveTime: account.resolveTime.toNumber(),
      };
    } catch (error) {
      console.error('[GoalChain] getOnchainMarket failed:', error);
      return null;
    }
  }

  async getSOLBalance(publicKey: PublicKey): Promise<number> {
    try {
      const balance = await this.connection.getBalance(publicKey);
      return balance / LAMPORTS_PER_SOL;
    } catch {
      return 0;
    }
  }
}

/** Map raw program errors to user-friendly messages. */
function friendlyBetError(message: string): string {
  if (message.includes('BettingLocked')) return 'Betting is locked for this market (kickoff passed).';
  if (message.includes('MarketNotOpen')) return 'This market is not open for betting.';
  if (message.includes('already in use')) {
    return 'You already have a bet on this outcome for this market.';
  }
  if (message.includes('insufficient lamports') || message.includes('Insufficient')) {
    return 'Insufficient SOL balance (get Devnet SOL from a faucet).';
  }
  if (message.includes('User rejected')) return 'Transaction was rejected in the wallet.';
  return message;
}

export const solanaClient = new SolanaClient();
export default SolanaClient;
